# Created By: Khalid Muslih
# Created Date: 12/17/2019
# Purpose: Install list servers and their users and copy them into a text file
# Instructions: you have to create the empty text file "userslist.txt" before running this playbook
---
- hosts: all
  gather_facts: yes
  become: yes
  ignore_errors: true
  tasks:
    - shell: "getent passwd | awk -F: '$3 > 1000 {print $1}'"
      when:
       - type == "ign"
       - env == "v"
      register: user_list
    - debug: var=user_list.stdout_lines
      when:
       - type == "ign"
       - env == "v"

    - local_action: lineinfile line={{inventory_hostname + '\n' +  user_list.stdout }} path=/etc/ansible/userslist.txt
      when:
       - type == "ign"
       - env == "v"
